# Generated by Django 2.1.2 on 2018-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=1024, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorypage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='offerpage',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=1024, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerpage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
