# Generated by Django 2.1.2 on 2018-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181021_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpage',
            name='code',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='vendor code'),
        ),
    ]
