# Generated by Django 2.1.2 on 2018-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181021_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerpage',
            name='display_in_selections',
            field=models.BooleanField(default=False),
        ),
    ]
