# Generated by Django 2.1 on 2018-11-01 15:43

import core.db.image
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_offerpage_display_in_selections'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified_at', models.DateTimeField(blank=True, verbose_name='last modification date')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('image', models.ImageField(default='images/no_photo.png', upload_to=core.db.image.upload_to, verbose_name='изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='_meta_title',
            field=models.CharField(blank=True, max_length=512, verbose_name='meta-tag title'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='_title',
            field=models.CharField(blank=True, max_length=512, verbose_name='H1 title'),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='_meta_title',
            field=models.CharField(blank=True, max_length=512, verbose_name='meta-tag title'),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='_title',
            field=models.CharField(blank=True, max_length=512, verbose_name='H1 title'),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='shop.Product'),
        ),
        migrations.AddField(
            model_name='offerimage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.OfferPage'),
        ),
    ]
