# Generated by Django 2.1 on 2018-11-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_Images'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimage',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=1024, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=1024, verbose_name='name'),
        ),
    ]
