# Generated by Django 2.1 on 2018-11-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_ImageName'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerimage',
            name='name',
        ),
    ]
